Algoritmo "semnome"
//Solicitar o nome
//e a idade de uma pessoa e informar ao usuário se
//ela já pode ou não tirar CNH
Var
nome:caracter
idade:inteiro
Inicio
      escreva("informe seu nome e sua idade : ")
      leia(nome,idade)
      se (idade>=18) entao
      escreval ( nome, "você pode tirar sua cnh ")
      senao
      escreva(nome,"  você não está apto a tirar a cnh ")
      fimse
      
      


     






Fimalgoritmo