Algoritmo "semnome"
//Solicite um
//valor e apresente as mensagens: “Valor positivo”, “Valor negativo” ou “Zero”
Var
valor:real
Inicio
      escreva("informe um valor : ")
      leia(valor)
      se (valor>0) entao
      escreval("o valor é positivo")
      fimse
      se (valor<0) entao
      escreval("o valor é negativo")
      fimse
      se (valor=0) entao
      escreval("o valor é zero")
      fimse


      
      
      
      


     






Fimalgoritmo