Algoritmo "semnome"
//Solicite dois valores
//(supostamente distintos) e apresente qual é o maior valor
Var
valor1,valor2:real
Inicio
      escreva("informe dois valores distintos : ")
      leia(valor1,valor2)
      se (valor1>valor2) entao
      escreval("o valor 1 é maior que o valor 2 ")
      senao
      escreval("o valor 2 é maior que o valor 1 ")
      fimse



      
      
      
      


     






Fimalgoritmo